name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step Completed
        run: echo "Hello World"
      - name: Second Step Completed
        run: echo "The process completed"

   
  
